# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296690d1b8075df63d7e4dd3209a2e9b67d280661851560d262efddccf2400018f0b4f65d6e29f5fa3381a3cd2da918bfd3a06c3d722e15494f420b054424a88

test:
  secret_key_base: 9ed5dc1ad46e60279b7b407a39014076e8d822ec76d23ab3c78fed895559fb393409c75f65fcffb9d76b2cb6067c3628e4699fa85fc6cbeaad009fa74b79a4e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
